-- ============================================================================
-- Test Procedures
-- ============================================================================

SET SERVEROUTPUT ON;

-- Test 1: Add Customer
DECLARE
    v_customer_id NUMBER;
BEGIN
    proc_add_customer(
        p_full_name => 'Test Customer Phase6',
        p_phone => '0788999999',
        p_address => 'Test Address, Kigali',
        p_meter_number => 'MT999999',
        p_status => 'ACTIVE',
        p_customer_id => v_customer_id
    );
    DBMS_OUTPUT.PUT_LINE('✅ Test 1 PASSED: Customer added with ID: ' || v_customer_id);
END;
/

-- Test 2: Record Meter Reading
DECLARE
    v_reading_id NUMBER;
    v_customer_id NUMBER;
BEGIN
    SELECT customer_id INTO v_customer_id 
    FROM customers 
    WHERE meter_number = 'MT999999';
    
    proc_record_meter_reading(
        p_customer_id => v_customer_id,
        p_reading_month => SYSDATE,
        p_previous_reading => 0,
        p_current_reading => 20,
        p_notes => 'Test reading for Phase 6',
        p_reading_id => v_reading_id
    );
    DBMS_OUTPUT.PUT_LINE('✅ Test 2 PASSED: Meter reading recorded. ID: ' || v_reading_id);
    DBMS_OUTPUT.PUT_LINE('   Note: Bill should be auto-generated by trigger');
END;
/

-- Test 3: Process Payment
DECLARE
    v_payment_id NUMBER;
    v_bill_id NUMBER;
BEGIN
    SELECT bill_id INTO v_bill_id
    FROM bills b
    INNER JOIN customers c ON b.customer_id = c.customer_id
    WHERE c.meter_number = 'MT999999'
    ORDER BY b.billing_period DESC
    FETCH FIRST 1 ROW ONLY;
    
    proc_process_payment(
        p_bill_id => v_bill_id,
        p_amount_paid => 10000,
        p_payment_method => 'CASH',
        p_reference_number => 'TEST_PHASE6_' || TO_CHAR(SYSDATE, 'HH24MISS'),
        p_received_by => 'Test Agent',
        p_payment_id => v_payment_id
    );
    DBMS_OUTPUT.PUT_LINE('✅ Test 3 PASSED: Payment processed. ID: ' || v_payment_id);
END;
/

-- Test 4: Update Overdue Bills
BEGIN
    proc_update_overdue_bills;
    DBMS_OUTPUT.PUT_LINE('✅ Test 4 PASSED: Overdue bills updated');
END;
/