-- ============================================================================
-- Water Billing System - PROCEDURES
-- ============================================================================
-- Procedures for business logic and operations
-- ============================================================================

-- ============================================================================
-- PROCEDURE 1: Add new customer
-- ============================================================================
CREATE OR REPLACE PROCEDURE proc_add_customer(
    p_full_name IN VARCHAR2,
    p_phone IN VARCHAR2,
    p_address IN VARCHAR2,
    p_meter_number IN VARCHAR2,
    p_status IN VARCHAR2 DEFAULT 'ACTIVE',
    p_customer_id OUT NUMBER
)
IS
BEGIN
    -- Validate status
    IF p_status NOT IN ('ACTIVE', 'INACTIVE', 'SUSPENDED') THEN
        RAISE_APPLICATION_ERROR(-20010, 'Invalid customer status');
    END IF;
    
    -- Generate customer ID
    SELECT seq_customer_id.NEXTVAL INTO p_customer_id FROM DUAL;
    
    -- Insert customer
    INSERT INTO customers (customer_id, full_name, phone, address, meter_number, status)
    VALUES (p_customer_id, p_full_name, p_phone, p_address, p_meter_number, p_status);
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Customer added successfully with ID: ' || p_customer_id);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20011, 'Phone number or meter number already exists');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- ============================================================================
-- PROCEDURE 2: Record meter reading
-- ============================================================================
CREATE OR REPLACE PROCEDURE proc_record_meter_reading(
    p_customer_id IN NUMBER,
    p_reading_month IN DATE,
    p_previous_reading IN NUMBER,
    p_current_reading IN NUMBER,
    p_notes IN VARCHAR2 DEFAULT NULL,
    p_reading_id OUT NUMBER
)
IS
    v_usage NUMBER(10,2);
    v_customer_status VARCHAR2(20);
BEGIN
    -- Validate customer exists and is active
    SELECT status INTO v_customer_status
    FROM customers
    WHERE customer_id = p_customer_id;
    
    IF v_customer_status != 'ACTIVE' THEN
        RAISE_APPLICATION_ERROR(-20020, 'Customer is not active');
    END IF;
    
    -- Validate readings
    IF p_current_reading < p_previous_reading THEN
        RAISE_APPLICATION_ERROR(-20021, 'Current reading must be >= previous reading');
    END IF;
    
    -- Check for duplicate reading in same month
    SELECT COUNT(*)
    INTO v_usage
    FROM meter_readings
    WHERE customer_id = p_customer_id
    AND TRUNC(reading_month, 'MM') = TRUNC(p_reading_month, 'MM');
    
    IF v_usage > 0 THEN
        RAISE_APPLICATION_ERROR(-20022, 'Reading already exists for this month');
    END IF;
    
    -- Generate reading ID
    SELECT seq_reading_id.NEXTVAL INTO p_reading_id FROM DUAL;
    
    -- Insert reading (trigger will calculate usage_m3)
    INSERT INTO meter_readings (reading_id, customer_id, reading_month, previous_reading, current_reading, notes)
    VALUES (p_reading_id, p_customer_id, p_reading_month, p_previous_reading, p_current_reading, p_notes);
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Meter reading recorded successfully. Reading ID: ' || p_reading_id);
    -- Note: Bill will be auto-generated by trigger
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20023, 'Customer not found');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- ============================================================================
-- PROCEDURE 3: Generate bill from reading (with tiered tariffs)
-- ============================================================================
CREATE OR REPLACE PROCEDURE proc_generate_bill(
    p_reading_id IN NUMBER,
    p_due_date IN DATE,
    p_bill_id OUT NUMBER
)
IS
    v_customer_id NUMBER(10);
    v_reading_month DATE;
    v_usage_m3 NUMBER(10,2);
    v_total_amount NUMBER(12,2);
    v_tier1_amount NUMBER(12,2);
    v_tier2_amount NUMBER(12,2);
    v_tier3_amount NUMBER(12,2);
    v_tier4_amount NUMBER(12,2);
    v_tier5_amount NUMBER(12,2);
    v_base_amount NUMBER(12,2);
BEGIN
    -- Get reading details
    SELECT customer_id, reading_month, usage_m3
    INTO v_customer_id, v_reading_month, v_usage_m3
    FROM meter_readings
    WHERE reading_id = p_reading_id;
    
    -- Calculate tiered amount using function
    v_total_amount := fn_get_tier_breakdown(
        p_usage_m3 => v_usage_m3,
        p_tier1_amount => v_tier1_amount,
        p_tier2_amount => v_tier2_amount,
        p_tier3_amount => v_tier3_amount,
        p_tier4_amount => v_tier4_amount,
        p_tier5_amount => v_tier5_amount,
        p_base_amount => v_base_amount
    );
    
    -- Generate bill ID
    SELECT seq_bill_id.NEXTVAL INTO p_bill_id FROM DUAL;
    
    -- Insert bill
    INSERT INTO bills (
        bill_id, customer_id, reading_id, billing_period, usage_m3,
        base_amount, tier1_amount, tier2_amount, tier3_amount, tier4_amount, tier5_amount,
        total_amount_due, due_date, status
    )
    VALUES (
        p_bill_id, v_customer_id, p_reading_id, v_reading_month, v_usage_m3,
        v_base_amount, v_tier1_amount, v_tier2_amount, v_tier3_amount, v_tier4_amount, v_tier5_amount,
        v_total_amount, p_due_date, 'PENDING'
    );
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Bill generated successfully. Bill ID: ' || p_bill_id || ', Amount: ' || v_total_amount);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20030, 'Reading not found');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- ============================================================================
-- PROCEDURE 4: Process payment
-- ============================================================================
CREATE OR REPLACE PROCEDURE proc_process_payment(
    p_bill_id IN NUMBER,
    p_amount_paid IN NUMBER,
    p_payment_method IN VARCHAR2,
    p_reference_number IN VARCHAR2 DEFAULT NULL,
    p_received_by IN VARCHAR2,
    p_payment_id OUT NUMBER
)
IS
    v_bill_amount NUMBER(12,2);
    v_total_paid NUMBER(12,2);
    v_bill_status VARCHAR2(20);
BEGIN
    -- Validate bill exists
    SELECT total_amount_due, status
    INTO v_bill_amount, v_bill_status
    FROM bills
    WHERE bill_id = p_bill_id;
    
    IF v_bill_status = 'PAID' THEN
        RAISE_APPLICATION_ERROR(-20040, 'Bill is already fully paid');
    END IF;
    
    IF v_bill_status = 'CANCELLED' THEN
        RAISE_APPLICATION_ERROR(-20041, 'Cannot process payment for cancelled bill');
    END IF;
    
    -- Validate payment method
    IF p_payment_method NOT IN ('CASH', 'MOMO PAY', 'BANK TRANSFER', 'CHEQUE', 'OTHER') THEN
        RAISE_APPLICATION_ERROR(-20042, 'Invalid payment method');
    END IF;
    
    -- Get total already paid
    SELECT NVL(SUM(amount_paid), 0)
    INTO v_total_paid
    FROM payments
    WHERE bill_id = p_bill_id;
    
    -- Check if overpayment
    IF (v_total_paid + p_amount_paid) > v_bill_amount THEN
        RAISE_APPLICATION_ERROR(-20043, 
            'Payment amount exceeds bill amount. Bill: ' || v_bill_amount || 
            ', Already paid: ' || v_total_paid || ', Payment: ' || p_amount_paid);
    END IF;
    
    -- Generate payment ID
    SELECT seq_payment_id.NEXTVAL INTO p_payment_id FROM DUAL;
    
    -- Insert payment
    INSERT INTO payments (payment_id, bill_id, payment_date, amount_paid, payment_method, reference_number, received_by)
    VALUES (p_payment_id, p_bill_id, SYSDATE, p_amount_paid, p_payment_method, p_reference_number, p_received_by);
    
    COMMIT;
    
    -- Status will be updated by trigger
    DBMS_OUTPUT.PUT_LINE('Payment processed successfully. Payment ID: ' || p_payment_id);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20044, 'Bill not found');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- ============================================================================
-- PROCEDURE 5: Update overdue bills status
-- ============================================================================
CREATE OR REPLACE PROCEDURE proc_update_overdue_bills
IS
    v_count NUMBER := 0;
BEGIN
    -- Update all pending bills past due date to overdue
    UPDATE bills
    SET status = 'OVERDUE'
    WHERE status = 'PENDING'
    AND due_date < SYSDATE;
    
    v_count := SQL%ROWCOUNT;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Updated ' || v_count || ' bills to OVERDUE status');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- ============================================================================
-- PROCEDURE 6: Setup tiered tariff rates
-- ============================================================================
CREATE OR REPLACE PROCEDURE proc_setup_tariff_rates(
    p_tier1_min IN NUMBER,
    p_tier1_max IN NUMBER,
    p_tier1_rate IN NUMBER,
    p_tier2_min IN NUMBER,
    p_tier2_max IN NUMBER,
    p_tier2_rate IN NUMBER,
    p_tier3_min IN NUMBER,
    p_tier3_max IN NUMBER,
    p_tier3_rate IN NUMBER,
    p_tier4_min IN NUMBER,
    p_tier4_max IN NUMBER,
    p_tier4_rate IN NUMBER,
    p_tier5_min IN NUMBER,
    p_tier5_max IN NUMBER,
    p_tier5_rate IN NUMBER
)
IS
    v_tariff_id NUMBER(10);
BEGIN
    -- Deactivate old rates
    UPDATE tariff_rates SET is_active = 'N', effective_to = SYSDATE - 1
    WHERE is_active = 'Y';
    
    -- Insert Tier 1
    SELECT seq_tariff_id.NEXTVAL INTO v_tariff_id FROM DUAL;
    INSERT INTO tariff_rates (tariff_id, tier_level, min_usage_m3, max_usage_m3, rate_per_m3, effective_from)
    VALUES (v_tariff_id, 1, p_tier1_min, p_tier1_max, p_tier1_rate, SYSDATE);
    
    -- Insert Tier 2
    SELECT seq_tariff_id.NEXTVAL INTO v_tariff_id FROM DUAL;
    INSERT INTO tariff_rates (tariff_id, tier_level, min_usage_m3, max_usage_m3, rate_per_m3, effective_from)
    VALUES (v_tariff_id, 2, p_tier2_min, p_tier2_max, p_tier2_rate, SYSDATE);
    
    -- Insert Tier 3
    SELECT seq_tariff_id.NEXTVAL INTO v_tariff_id FROM DUAL;
    INSERT INTO tariff_rates (tariff_id, tier_level, min_usage_m3, max_usage_m3, rate_per_m3, effective_from)
    VALUES (v_tariff_id, 3, p_tier3_min, p_tier3_max, p_tier3_rate, SYSDATE);
    
    -- Insert Tier 4
    SELECT seq_tariff_id.NEXTVAL INTO v_tariff_id FROM DUAL;
    INSERT INTO tariff_rates (tariff_id, tier_level, min_usage_m3, max_usage_m3, rate_per_m3, effective_from)
    VALUES (v_tariff_id, 4, p_tier4_min, p_tier4_max, p_tier4_rate, SYSDATE);
    
    -- Insert Tier 5
    SELECT seq_tariff_id.NEXTVAL INTO v_tariff_id FROM DUAL;
    INSERT INTO tariff_rates (tariff_id, tier_level, min_usage_m3, max_usage_m3, rate_per_m3, effective_from)
    VALUES (v_tariff_id, 5, p_tier5_min, p_tier5_max, p_tier5_rate, SYSDATE);
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('Tariff rates setup completed successfully');
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

COMMIT;
