-- ============================================================================
-- Expand Sample Data to 100-500 rows per table
-- ============================================================================

SET SERVEROUTPUT ON;

-- Expand Customers to 100+
DECLARE
    v_customer_id NUMBER;
    v_count NUMBER := 0;
BEGIN
    FOR i IN 6..100 LOOP
        BEGIN
            proc_add_customer(
                p_full_name => 'Customer ' || i || ' Name',
                p_phone => '0788' || LPAD(i, 6, '0'),
                p_address => 'Address ' || i || ', Kigali, Rwanda',
                p_meter_number => 'MT' || LPAD(i, 6, '0'),
                p_status => CASE WHEN MOD(i, 10) = 0 THEN 'INACTIVE' ELSE 'ACTIVE' END,
                p_customer_id => v_customer_id
            );
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Skip if duplicate
        END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Added ' || v_count || ' more customers');
END;
/

-- Expand Meter Readings (3 months for each active customer)
DECLARE
    v_reading_id NUMBER;
    v_prev_reading NUMBER;
    v_curr_reading NUMBER;
    v_count NUMBER := 0;
BEGIN
    FOR cust_rec IN (SELECT customer_id FROM customers WHERE status = 'ACTIVE') LOOP
        -- Get last reading for this customer
        SELECT NVL(MAX(current_reading), 0) INTO v_prev_reading
        FROM meter_readings
        WHERE customer_id = cust_rec.customer_id;
        
        -- January 2024 (if not exists)
        BEGIN
            v_curr_reading := v_prev_reading + ROUND(DBMS_RANDOM.VALUE(5, 30));
            proc_record_meter_reading(
                p_customer_id => cust_rec.customer_id,
                p_reading_month => TO_DATE('2024-01-15', 'YYYY-MM-DD'),
                p_previous_reading => v_prev_reading,
                p_current_reading => v_curr_reading,
                p_notes => 'Initial reading',
                p_reading_id => v_reading_id
            );
            v_prev_reading := v_curr_reading;
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Skip if duplicate
        END;
        
        -- February 2024 (if not exists)
        BEGIN
            v_curr_reading := v_prev_reading + ROUND(DBMS_RANDOM.VALUE(5, 30));
            proc_record_meter_reading(
                p_customer_id => cust_rec.customer_id,
                p_reading_month => TO_DATE('2024-02-15', 'YYYY-MM-DD'),
                p_previous_reading => v_prev_reading,
                p_current_reading => v_curr_reading,
                p_notes => NULL,
                p_reading_id => v_reading_id
            );
            v_prev_reading := v_curr_reading;
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Skip if duplicate
        END;
        
        -- March 2024 (if not exists)
        BEGIN
            v_curr_reading := v_prev_reading + ROUND(DBMS_RANDOM.VALUE(5, 30));
            proc_record_meter_reading(
                p_customer_id => cust_rec.customer_id,
                p_reading_month => TO_DATE('2024-03-15', 'YYYY-MM-DD'),
                p_previous_reading => v_prev_reading,
                p_current_reading => v_curr_reading,
                p_notes => NULL,
                p_reading_id => v_reading_id
            );
            v_prev_reading := v_curr_reading;
            v_count := v_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Skip if duplicate
        END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Added ' || v_count || ' more meter readings');
    DBMS_OUTPUT.PUT_LINE('Note: Bills are automatically generated by triggers');
END;
/

-- Add more payments (for bills that don't have full payment)
DECLARE
    v_payment_id NUMBER;
    v_payment_count NUMBER := 0;
BEGIN
    FOR bill_rec IN (
        SELECT b.bill_id, b.total_amount_due, 
               NVL(SUM(p.amount_paid), 0) as paid
        FROM bills b
        LEFT JOIN payments p ON b.bill_id = p.bill_id
        GROUP BY b.bill_id, b.total_amount_due
        HAVING NVL(SUM(p.amount_paid), 0) < b.total_amount_due
        FETCH FIRST 50 ROWS ONLY
    ) LOOP
        BEGIN
            proc_process_payment(
                p_bill_id => bill_rec.bill_id,
                p_amount_paid => bill_rec.total_amount_due - bill_rec.paid,
                p_payment_method => CASE MOD(bill_rec.bill_id, 4)
                    WHEN 0 THEN 'CASH'
                    WHEN 1 THEN 'MOMO PAY'
                    WHEN 2 THEN 'BANK TRANSFER'
                    ELSE 'CHEQUE'
                END,
                p_reference_number => 'PAY' || LPAD(bill_rec.bill_id, 6, '0') || '_' || TO_CHAR(SYSDATE, 'HH24MISS'),
                p_received_by => 'Agent ' || (MOD(bill_rec.bill_id, 5) + 1),
                p_payment_id => v_payment_id
            );
            v_payment_count := v_payment_count + 1;
        EXCEPTION
            WHEN OTHERS THEN NULL; -- Skip if error
        END;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Added ' || v_payment_count || ' more payments');
END;
/

COMMIT;

-- Show final counts
SELECT 'CUSTOMERS' as table_name, COUNT(*) as row_count FROM customers
UNION ALL
SELECT 'TARIFF_RATES', COUNT(*) FROM tariff_rates
UNION ALL
SELECT 'METER_READINGS', COUNT(*) FROM meter_readings
UNION ALL
SELECT 'BILLS', COUNT(*) FROM bills
UNION ALL
SELECT 'PAYMENTS', COUNT(*) FROM payments;