-- ============================================================================
-- Water Billing System - TEST/DEMO SCRIPT
-- ============================================================================
-- This script demonstrates all features of the Water Billing System
-- ============================================================================

SET SERVEROUTPUT ON SIZE 1000000;

-- Enable DBMS_OUTPUT
BEGIN
    DBMS_OUTPUT.ENABLE(1000000);
END;
/

PROMPT ============================================================================
PROMPT WATER BILLING AND USAGE MANAGEMENT SYSTEM - TEST SCRIPT
PROMPT ============================================================================
PROMPT This script demonstrates all features of the system
PROMPT ============================================================================
PROMPT

-- ============================================================================
-- TEST 1: Display Current Tariff Rates
-- ============================================================================
PROMPT
PROMPT TEST 1: Display Current Tariff Rates
PROMPT ============================================================================
SELECT 
    tier_level as "Tier",
    min_usage_m3 as "Min (m3)",
    NVL(max_usage_m3, 'Unlimited') as "Max (m3)",
    rate_per_m3 as "Rate (RWF/m3)",
    TO_CHAR(effective_from, 'DD-MON-YYYY') as "Effective From"
FROM tariff_rates
WHERE is_active = 'Y'
ORDER BY tier_level;

-- ============================================================================
-- TEST 2: Display All Customers
-- ============================================================================
PROMPT
PROMPT TEST 2: Display All Customers
PROMPT ============================================================================
SELECT 
    customer_id as "ID",
    full_name as "Name",
    phone as "Phone",
    meter_number as "Meter #",
    status as "Status"
FROM customers
ORDER BY customer_id;

-- ============================================================================
-- TEST 3: Add a New Customer
-- ============================================================================
PROMPT
PROMPT TEST 3: Add a New Customer
PROMPT ============================================================================
DECLARE
    v_customer_id NUMBER;
BEGIN
    proc_add_customer(
        p_full_name => 'Test Customer',
        p_phone => '0788999999',
        p_address => 'Test Address, Kigali',
        p_meter_number => 'MT999999',
        p_status => 'ACTIVE',
        p_customer_id => v_customer_id
    );
    DBMS_OUTPUT.PUT_LINE('New customer created with ID: ' || v_customer_id);
END;
/

-- ============================================================================
-- TEST 4: Record a Meter Reading (will auto-generate bill)
-- ============================================================================
PROMPT
PROMPT TEST 4: Record a Meter Reading (Bill will be auto-generated)
PROMPT ============================================================================
DECLARE
    v_reading_id NUMBER;
    v_customer_id NUMBER;
BEGIN
    -- Get the test customer ID
    SELECT customer_id INTO v_customer_id 
    FROM customers 
    WHERE meter_number = 'MT999999';
    
    -- Record reading
    proc_record_meter_reading(
        p_customer_id => v_customer_id,
        p_reading_month => SYSDATE,
        p_previous_reading => 0,
        p_current_reading => 15,
        p_notes => 'Test reading',
        p_reading_id => v_reading_id
    );
    DBMS_OUTPUT.PUT_LINE('Meter reading recorded. Reading ID: ' || v_reading_id);
    DBMS_OUTPUT.PUT_LINE('Bill should be automatically generated by trigger.');
END;
/

-- ============================================================================
-- TEST 5: Display Bills for the Test Customer
-- ============================================================================
PROMPT
PROMPT TEST 5: Display Bills for Test Customer
PROMPT ============================================================================
SELECT 
    b.bill_id as "Bill ID",
    c.full_name as "Customer",
    TO_CHAR(b.billing_period, 'DD-MON-YYYY') as "Period",
    b.usage_m3 as "Usage (m3)",
    b.base_amount as "Base",
    b.tier1_amount as "Tier1",
    b.tier2_amount as "Tier2",
    b.total_amount_due as "Total",
    TO_CHAR(b.due_date, 'DD-MON-YYYY') as "Due Date",
    b.status as "Status"
FROM bills b
INNER JOIN customers c ON b.customer_id = c.customer_id
WHERE c.meter_number = 'MT999999'
ORDER BY b.billing_period DESC;

-- ============================================================================
-- TEST 6: Process a Payment
-- ============================================================================
PROMPT
PROMPT TEST 6: Process a Payment
PROMPT ============================================================================
DECLARE
    v_payment_id NUMBER;
    v_bill_id NUMBER;
    v_customer_id NUMBER;
BEGIN
    -- Get bill ID for test customer
    SELECT b.bill_id INTO v_bill_id
    FROM bills b
    INNER JOIN customers c ON b.customer_id = c.customer_id
    WHERE c.meter_number = 'MT999999'
    ORDER BY b.billing_period DESC
    FETCH FIRST 1 ROW ONLY;
    
    -- Process payment
    proc_process_payment(
        p_bill_id => v_bill_id,
        p_amount_paid => 10000,
        p_payment_method => 'CASH',
        p_reference_number => 'TEST001',
        p_received_by => 'Test Agent',
        p_payment_id => v_payment_id
    );
    DBMS_OUTPUT.PUT_LINE('Payment processed. Payment ID: ' || v_payment_id);
END;
/

-- ============================================================================
-- TEST 7: Check Bill Status After Payment
-- ============================================================================
PROMPT
PROMPT TEST 7: Check Bill Status After Payment
PROMPT ============================================================================
SELECT 
    b.bill_id as "Bill ID",
    b.total_amount_due as "Amount Due",
    NVL(SUM(p.amount_paid), 0) as "Amount Paid",
    (b.total_amount_due - NVL(SUM(p.amount_paid), 0)) as "Balance",
    b.status as "Status"
FROM bills b
LEFT JOIN payments p ON b.bill_id = p.bill_id
INNER JOIN customers c ON b.customer_id = c.customer_id
WHERE c.meter_number = 'MT999999'
GROUP BY b.bill_id, b.total_amount_due, b.status
ORDER BY b.billing_period DESC;

-- ============================================================================
-- TEST 8: Test Tiered Calculation Function
-- ============================================================================
PROMPT
PROMPT TEST 8: Test Tiered Calculation Function
PROMPT ============================================================================
DECLARE
    v_total NUMBER(12,2);
    v_tier1 NUMBER(12,2);
    v_tier2 NUMBER(12,2);
    v_tier3 NUMBER(12,2);
    v_tier4 NUMBER(12,2);
    v_tier5 NUMBER(12,2);
    v_base NUMBER(12,2);
BEGIN
    DBMS_OUTPUT.PUT_LINE('Testing tiered calculation for 35 m3 usage:');
    v_total := fn_get_tier_breakdown(
        p_usage_m3 => 35,
        p_tier1_amount => v_tier1,
        p_tier2_amount => v_tier2,
        p_tier3_amount => v_tier3,
        p_tier4_amount => v_tier4,
        p_tier5_amount => v_tier5,
        p_base_amount => v_base
    );
    DBMS_OUTPUT.PUT_LINE('Base Amount: ' || TO_CHAR(v_base, '999,999.99') || ' RWF');
    DBMS_OUTPUT.PUT_LINE('Tier 1 (0-10 m3): ' || TO_CHAR(v_tier1, '999,999.99') || ' RWF');
    DBMS_OUTPUT.PUT_LINE('Tier 2 (11-20 m3): ' || TO_CHAR(v_tier2, '999,999.99') || ' RWF');
    DBMS_OUTPUT.PUT_LINE('Tier 3 (21-30 m3): ' || TO_CHAR(v_tier3, '999,999.99') || ' RWF');
    DBMS_OUTPUT.PUT_LINE('Tier 4 (31-50 m3): ' || TO_CHAR(v_tier4, '999,999.99') || ' RWF');
    DBMS_OUTPUT.PUT_LINE('Tier 5 (51+ m3): ' || TO_CHAR(v_tier5, '999,999.99') || ' RWF');
    DBMS_OUTPUT.PUT_LINE('Total Amount: ' || TO_CHAR(v_total, '999,999.99') || ' RWF');
END;
/

-- ============================================================================
-- TEST 9: Get Customer Balance
-- ============================================================================
PROMPT
PROMPT TEST 9: Get Customer Balance
PROMPT ============================================================================
DECLARE
    v_balance NUMBER(12,2);
    v_customer_id NUMBER;
BEGIN
    SELECT customer_id INTO v_customer_id 
    FROM customers 
    WHERE meter_number = 'MT001234';
    
    v_balance := fn_get_customer_balance(v_customer_id);
    DBMS_OUTPUT.PUT_LINE('Customer Balance: ' || TO_CHAR(v_balance, '999,999,999.99') || ' RWF');
END;
/

-- ============================================================================
-- TEST 10: Generate Usage Report
-- ============================================================================
PROMPT
PROMPT TEST 10: Generate Usage Report (All Customers)
PROMPT ============================================================================
EXEC proc_usage_report;

-- ============================================================================
-- TEST 11: Generate Payment Report
-- ============================================================================
PROMPT
PROMPT TEST 11: Generate Payment Report
PROMPT ============================================================================
EXEC proc_payment_report;

-- ============================================================================
-- TEST 12: Generate Overdue Accounts Report
-- ============================================================================
PROMPT
PROMPT TEST 12: Generate Overdue Accounts Report
PROMPT ============================================================================
-- First, update some bills to overdue status
EXEC proc_update_overdue_bills;
-- Then generate report
EXEC proc_overdue_accounts_report;

-- ============================================================================
-- TEST 13: Generate Customer Statement
-- ============================================================================
PROMPT
PROMPT TEST 13: Generate Customer Statement
PROMPT ============================================================================
DECLARE
    v_customer_id NUMBER;
BEGIN
    SELECT customer_id INTO v_customer_id 
    FROM customers 
    WHERE meter_number = 'MT001234';
    
    proc_customer_statement(v_customer_id);
END;
/

-- ============================================================================
-- TEST 14: Generate Monthly Summary
-- ============================================================================
PROMPT
PROMPT TEST 14: Generate Monthly Summary Report
PROMPT ============================================================================
EXEC proc_monthly_summary(TO_DATE('2024-03-01', 'YYYY-MM-DD'));

-- ============================================================================
-- TEST 15: Test Validation - Try to add duplicate meter number
-- ============================================================================
PROMPT
PROMPT TEST 15: Test Validation - Try to add duplicate meter number
PROMPT ============================================================================
DECLARE
    v_customer_id NUMBER;
BEGIN
    BEGIN
        proc_add_customer(
            p_full_name => 'Duplicate Test',
            p_phone => '0788888888',
            p_address => 'Test',
            p_meter_number => 'MT001234', -- This already exists
            p_status => 'ACTIVE',
            p_customer_id => v_customer_id
        );
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Validation works! Error: ' || SQLERRM);
    END;
END;
/

-- ============================================================================
-- TEST 16: Test Validation - Try invalid meter reading
-- ============================================================================
PROMPT
PROMPT TEST 16: Test Validation - Try invalid meter reading (current < previous)
PROMPT ============================================================================
DECLARE
    v_reading_id NUMBER;
    v_customer_id NUMBER;
BEGIN
    SELECT customer_id INTO v_customer_id 
    FROM customers 
    WHERE meter_number = 'MT001234';
    
    BEGIN
        proc_record_meter_reading(
            p_customer_id => v_customer_id,
            p_reading_month => SYSDATE,
            p_previous_reading => 100,
            p_current_reading => 50, -- Invalid: current < previous
            p_notes => 'Test invalid',
            p_reading_id => v_reading_id
        );
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Validation works! Error: ' || SQLERRM);
    END;
END;
/

PROMPT
PROMPT ============================================================================
PROMPT ALL TESTS COMPLETED!
PROMPT ============================================================================
PROMPT
PROMPT Summary of features tested:
PROMPT - Customer management
PROMPT - Meter reading recording
PROMPT - Automatic bill generation (via triggers)
PROMPT - Payment processing
PROMPT - Tiered tariff calculations
PROMPT - Report generation (usage, payments, overdue, statements, monthly summary)
PROMPT - Data validation and error handling
PROMPT ============================================================================

